### ISSUE TITLE
Directories are not being created when running biox run

### ISSUE THREAD

**Issue by nizardrou** [biosails/BioX-Workflow-Command#19]
I recently added jellyfish to the QC workflow, but when I run biox run, it does not create the directory structure (data/analysis/Sample_*).

The workflow is at,
`/scratch/gencore/170321_SN7001341_0225_AC9V19ACXX/Unaligned/Project_Stephane_Boissinot/de_novo_genome_large_multi-libraries.yml`

**Comment by jerowe** [comment]
You didn't specify -outdir in your local rule, and so biox does not create it.

**Comment by jerowe** [comment]
Ok, they are still not being created. This is a really weird bug.

```
---
global:
  - indir: data/processed
  - outdir: data/analysis
  - analysis_dir: data/analysis
  - root: data/analysis
  - trimmomatic_dir: 'data/processed/{$sample}/trimmomatic'
  - trimmomatic: 'data/processed/{$sample}/trimmomatic'
  - raw_fastqc_dir: 'data/processed/{$sample}'
  - raw_fastqc: 'data/processed/{$sample}'
  - sample_rule: (Sample.*)$
  - by_sample_outdir: 1
  - find_by_dir: 1
  - wait: 0
  - READ1: '{$self->raw_fastqc_dir}/{$sample}_read1.fastq.gz'
  - READ2: '{$self->raw_fastqc_dir}/{$sample}_read2.fastq.gz'
  - TR1: '{$self->trimmomatic_dir}/{$sample}_read1_trimmomatic'
  - TR2: '{$self->trimmomatic_dir}/{$sample}_read2_trimmomatic'
  - jellyfish_dir: 'data/JANALYSIS/{$sample}/jellyfish'
  - HPC:
      - account: gencore
rules:
  - pre_assembly_jellyfishCount:
      local:
        - create_outdir: 1
        - outdir: '{$self->jellyfish_dir}'
        - INPUT:
            - '{$self->TR1}_1PE.fastq.gz'
            - '{$self->TR2}_2PE.fastq.gz'
        - OUTPUT: '{$self->jellyfish_dir}/{$sample}.jf'
        - HPC:
            - cpus_per_task: 24
            - walltime: 24:00:00
            - mem: 98GB
            - partition: serial
            - module: gencore gencore_dev anaconda/2-4.1.1
      process: |
        #TASK tags={$sample}
        mkdir -p {$self->outdir} \
        source activate /scratch/nd48/software/my_analysis/ && \
        jellyfish count \
            -m 21 \
            -s 100M \
            -t 24 \
            -C \
            -o {$self->OUTPUT} \
            <(zcat {$self->INPUT->[0]}) <(zcat {$self->INPUT->[1]})
  - pre_assembly_jellyfishHisto:
      local:
        - outdir: '{$self->jellyfish_dir}'
        - INPUT: '{$self->jellyfish_dir}/{$sample}.jf'
        - OUTPUT: '{$self->jellyfish_dir}/{$sample}.histo'
        - HPC:
            - cpus_per_task: 24
            - walltime: 04:00:00
            - mem: 30GB
            - partition: serial
            - module: gencore gencore_dev anaconda/2-4.1.1
            - deps: pre_assembly_jellyfishCount
      process: |
        #TASK tags={$sample}
        source activate /scratch/nd48/software/my_analysis/ && \
        jellyfish histo -t 24 {$self->INPUT} > {$self->OUTPUT}
```
