### ISSUE TITLE
Add sample sets

### ISSUE THREAD

**Issue by jerowe** [biosails/BioX-Workflow-Command#45]
Sometimes a sample does not exactly the specified structure, or we have multiple indirs.

Introduce sample sets, and/or multiple indirs.

```
- sample_set:
   - set:
       - indir: 'dataset/1'
        - sample_rule: '(Sample_.*).fastq
    - set: 
       - indir: 'dataset/2'
       - sample_rule: '(Sample_.*).fastq
```
