### ISSUE TITLE
local HPC overwrites global HPC

### ISSUE THREAD

**Issue by jerowe** [biosails/BioX-Workflow-Command#7]
They should be merged

```
global:
   - HPC:
       account: gencore
rules:
  - rule1:
       local:
          - HPC:
              walltime: '00:40:00'
```
Should result in

```
###HPC DIRECTIVES
#HPC jobname=rule1
#HPC walltime=00:40:00
#HPC account=gencore
```

Its missing the account.

Instead it gets:

```
###HPC DIRECTIVES
#HPC jobname=rule1
#HPC account=gencore
```
